# Generated by Django 5.2.7 on 2025-10-16 00:06

from django.utils import timezone
from django.db import migrations


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return

    superuser = User.objects.create_superuser(
        username="admin",
        email="admin@admin.com",
        password="admin12345",
        last_login=timezone.now(),
    )

    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
